// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"

	"encore.dev/types/uuid"
)

type Note struct {
	ID               uuid.UUID
	EasinessFactor   float64
	RepetitionNumber int32
	Interval         int32
	NoteFront        string
	NoteBack         string
	NextReview       time.Time
	IsLearning       bool
}
